language: node_js
node_js:
 - "lts/*"

before_install: 
  - yarn install

deploy:
  provider: firebase
  token:
    secure: FBxkvgjZ+Q4C2DUYAjxedmuDPoimwywUoFVA+qvRKJjcD/MlJR/XsXDuCD8kI2L0shEY/Vc+Q9RCKMhci7/U+liImLGEmbRtgWs9OX5mEIqzLYLS5eQyIxyuLmbUaILBEo9S9lB79shqgFS/SmXXhTZNqhMog45KaP2TspKXeRdOZc53CkoABAFfiHfQYIAVlkaZd96ILucTOE7SPXMMoIqqehT0XqBFx+BwY8ofodTyqQvAK9mySwapilKNZV/Dj1jqmVlI/R7geQSELHrfJGRvyKptrkMTJu6P4tAHjG23iSPQyHmF3C9QoeWvkrgErSkUz0t27CGsIgNi8hrVGvkYNyAVlPRCPl8lBXsSSBfhR1rNesK85dkuwMJrFfu+jVASPWwT+sTXOrIwONBZzqjKpgFfflUbRh6gMyEezf6PxSfnoi95CJ0mvzROcYS+h8ZUUNfHPsTypGVK9azsu6UWFkkIPO+hjZIRp22YI6XUJct0G0QEJAA4Npu4faFxn9689qctZnea0pdKMyWXbofL1OH6d4pNTcgfG4qb3k9sD315cNtyQGBbVVq6EL4KAeyHeObWsTSYlilHWRmPGNNpJtSuzkxJbXHZm2Xn9lqtd5/cWnqHq/Mveb+loOTdFG1vXr8ewmq1nWpDOs8n9ag3MU2YQ50hHF7PyHs8N2w=