export const ADD_MATCH = 'ADD_MATCH';
export const UPDATE_MATCH = 'UPDATE_MATCH';
export const RECIEVE_MATCHES = 'RECIEVE_MATCHES';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const UPDATE_USER = 'UPDATE_USER';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';

export const USERS_FETCHED = 'USERS_FETCHED';
